// lib/password-reset.ts
// Server-side logic for the 6-digit password-reset OTP flow.
//
// SECURITY MODEL
// ──────────────
// • Codes are generated by Supabase's signInWithOtp (cryptographically
//   secure). We never store or transport the code through our own DB —
//   verification is delegated to Supabase's verifyOtp. A dump of our
//   `password_reset_codes` table reveals no code material.
//
// • We still wrap Supabase's OTP with our own:
//     - strict 2-minute expiry (enforced here regardless of Supabase's
//       dashboard OTP expiry setting — defense in depth)
//     - per-code attempt cap (5 wrong tries → code invalidated)
//     - per-email rate limit     (1 code / 60 s, 5 codes / hour)
//     - per-IP   rate limit      (10 requests / 15 min, 20 verifies / 15 min)
//     - single-use enforcement   (consumed_at set on first success)
//
// • Constant-error-message policy: we never signal whether an email
//   is registered, whether a code existed, or whether it expired vs.
//   was wrong, to callers. The server logs the precise reason.

import type { NextRequest } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/server";

// ─── Tunables ─────────────────────────────────────────────────
export const CODE_TTL_SECONDS         = 120;   // 2 minutes, hard requirement
export const MAX_ATTEMPTS_PER_CODE    = 5;
export const REQUEST_COOLDOWN_SECONDS = 60;    // min time between codes for one email
export const REQUEST_PER_EMAIL_HOUR   = 5;
export const REQUEST_PER_IP_15M       = 10;
export const VERIFY_PER_IP_15M        = 20;

// ─── Event kinds ──────────────────────────────────────────────
export type AuthEventKind =
  | "reset_request"
  | "reset_request_rl"    // rate-limited at the request endpoint
  | "reset_verify_ok"
  | "reset_verify_fail"
  | "reset_verify_rl";    // rate-limited at the verify endpoint

// ─── IP / UA extraction ───────────────────────────────────────
// x-forwarded-for may be a comma-separated list appended by each
// proxy; the left-most entry is the original client.
export function getClientIp(req: NextRequest): string {
  const xff = req.headers.get("x-forwarded-for");
  if (xff) {
    const first = xff.split(",")[0]?.trim();
    if (first) return first;
  }
  return (
    req.headers.get("x-real-ip") ??
    req.headers.get("cf-connecting-ip") ??
    "unknown"
  );
}

export function getUserAgent(req: NextRequest): string {
  return (req.headers.get("user-agent") ?? "").slice(0, 400);
}

// ─── Audit log ────────────────────────────────────────────────
export async function logAuthEvent(
  kind: AuthEventKind,
  { email, ip, success }: { email?: string | null; ip?: string; success?: boolean },
): Promise<void> {
  try {
    await supabaseAdmin.from("auth_events").insert({
      kind,
      email:   email?.toLowerCase() ?? null,
      ip:      ip ?? null,
      success: success ?? null,
    });
  } catch (err) {
    // Never let audit failures bubble into the auth path.
    console.error("[auth_events] insert failed:", (err as Error).message);
  }
}

// ─── Rate-limit checks ────────────────────────────────────────
// All counts are DB-backed — survive restart and scale across
// instances. The `reset_request_rl` and `reset_verify_rl` events
// themselves DO NOT count toward future limits (we filter on the
// allowed kinds only).

async function countEvents(args: {
  kind:   AuthEventKind;
  email?: string;
  ip?:    string;
  windowSeconds: number;
}): Promise<number> {
  const since = new Date(Date.now() - args.windowSeconds * 1000).toISOString();
  let q = supabaseAdmin
    .from("auth_events")
    .select("id", { count: "exact", head: true })
    .eq("kind", args.kind)
    .gte("occurred_at", since);
  if (args.email) q = q.eq("email", args.email.toLowerCase());
  if (args.ip)    q = q.eq("ip", args.ip);
  const { count, error } = await q;
  if (error) {
    console.error("[rate-limit] count failed:", error.message);
    // Fail closed on infra errors: act as if limit is hit.
    return Number.MAX_SAFE_INTEGER;
  }
  return count ?? 0;
}

export interface RateLimitVerdict {
  ok:       boolean;
  retryInSeconds?: number;
  reason?:  string;
}

export async function checkRequestRateLimit(
  email: string,
  ip:    string,
): Promise<RateLimitVerdict> {
  // 1. Per-IP: max 10 requests / 15 min
  const ipCount = await countEvents({ kind: "reset_request", ip, windowSeconds: 900 });
  if (ipCount >= REQUEST_PER_IP_15M) {
    return { ok: false, retryInSeconds: 900, reason: "ip_limit" };
  }

  // 2. Per-email hourly: max 5 / hour
  const emailHourly = await countEvents({ kind: "reset_request", email, windowSeconds: 3600 });
  if (emailHourly >= REQUEST_PER_EMAIL_HOUR) {
    return { ok: false, retryInSeconds: 3600, reason: "email_hourly_limit" };
  }

  // 3. Per-email cooldown: 1 code / 60 s
  const emailCooldown = await countEvents({
    kind: "reset_request", email, windowSeconds: REQUEST_COOLDOWN_SECONDS,
  });
  if (emailCooldown >= 1) {
    return { ok: false, retryInSeconds: REQUEST_COOLDOWN_SECONDS, reason: "email_cooldown" };
  }

  return { ok: true };
}

export async function checkVerifyRateLimit(ip: string): Promise<RateLimitVerdict> {
  const ipCount = await countEvents({
    kind: "reset_verify_fail", ip, windowSeconds: 900,
  });
  if (ipCount >= VERIFY_PER_IP_15M) {
    return { ok: false, retryInSeconds: 900, reason: "ip_verify_limit" };
  }
  return { ok: true };
}

// ─── Code record lifecycle ────────────────────────────────────
export interface ResetCodeRow {
  id:          string;
  email:       string;
  user_id:     string | null;
  created_at:  string;
  expires_at:  string;
  consumed_at: string | null;
  attempts:    number;
  ip:          string | null;
  user_agent:  string | null;
}

/** Invalidate any still-active codes for this email so only the newest is usable. */
export async function invalidateActiveCodesFor(email: string): Promise<void> {
  await supabaseAdmin
    .from("password_reset_codes")
    .update({ consumed_at: new Date().toISOString() })
    .eq("email", email.toLowerCase())
    .is("consumed_at", null);
}

/** Record that we issued a new code; returns the row id. */
export async function recordIssuedCode(args: {
  email:     string;
  userId?:   string | null;
  ip:        string;
  userAgent: string;
}): Promise<string> {
  const now = new Date();
  const expires = new Date(now.getTime() + CODE_TTL_SECONDS * 1000);
  const { data, error } = await supabaseAdmin
    .from("password_reset_codes")
    .insert({
      email:      args.email.toLowerCase(),
      user_id:    args.userId ?? null,
      created_at: now.toISOString(),
      expires_at: expires.toISOString(),
      ip:         args.ip,
      user_agent: args.userAgent,
    })
    .select("id")
    .single();
  if (error || !data) {
    throw new Error(`Failed to record reset code: ${error?.message}`);
  }
  return data.id as string;
}

/** Most recent active (not consumed, not expired) code row for an email. */
export async function findActiveCode(email: string): Promise<ResetCodeRow | null> {
  const { data, error } = await supabaseAdmin
    .from("password_reset_codes")
    .select("*")
    .eq("email", email.toLowerCase())
    .is("consumed_at", null)
    .gte("expires_at", new Date().toISOString())
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (error) {
    console.error("[findActiveCode] query error:", error.message);
    return null;
  }
  return (data as ResetCodeRow | null) ?? null;
}

export async function incrementAttempts(codeId: string): Promise<number> {
  // Fetch → increment → write-back. A race here at worst off-by-one on the
  // counter, which is fine — the cap is approximate and defense-in-depth.
  const { data } = await supabaseAdmin
    .from("password_reset_codes")
    .select("attempts")
    .eq("id", codeId)
    .single();
  const next = ((data?.attempts as number | undefined) ?? 0) + 1;
  await supabaseAdmin
    .from("password_reset_codes")
    .update({ attempts: next })
    .eq("id", codeId);
  return next;
}

export async function markConsumed(codeId: string): Promise<void> {
  await supabaseAdmin
    .from("password_reset_codes")
    .update({ consumed_at: new Date().toISOString() })
    .eq("id", codeId);
}
